apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rag-chatbot
  template:
    metadata:
      labels:
        app: rag-chatbot
    spec:
      containers:
      - name: api
        image: ghcr.io/YOUR_USER/rag-chatbot:latest
        ports:
        - containerPort: 8000
        env:
        - name: CONFIG_PATH
          value: /app/config.yaml
        volumeMounts:
        - name: vectorstore
          mountPath: /app/embeddings
      volumes:
      - name: vectorstore
        emptyDir: {}